import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';

// Uses the installed Edge browser and Node's native WebSocket; no dependencies.
const browser = process.env.BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
const artifacts = resolve('artifacts');
await mkdir(artifacts, { recursive: true });
const child = spawn(browser, ['--headless=new', '--no-first-run', '--no-default-browser-check', '--disable-extensions', '--remote-debugging-port=0', `--user-data-dir=${resolve('.browser-profile')}`, 'about:blank'], { windowsHide: true, stdio: ['ignore', 'ignore', 'pipe'] });
let ws, id = 0;
const pending = new Map(), errors = [];
const endpoint = await new Promise((yes, no) => {
  const timeout = setTimeout(() => no(new Error('Browser did not start within 20 seconds.')), 20000);
  child.on('error', no);
  child.stderr.on('data', data => { const match = String(data).match(/DevTools listening on (ws:\/\/\S+)/); if (match) { clearTimeout(timeout); yes(match[1]); } });
});
try {
  const origin = endpoint.replace(/^ws:/, 'http:').split('/devtools')[0];
  const pages = await (await fetch(`${origin}/json/list`)).json();
  ws = new WebSocket(pages.find(p => p.type === 'page').webSocketDebuggerUrl);
  await new Promise((yes, no) => { ws.onopen = yes; ws.onerror = no; });
  ws.onmessage = ({ data }) => {
    const message = JSON.parse(data);
    if (message.id) { const p = pending.get(message.id); pending.delete(message.id); if (p) { clearTimeout(p.timer); message.error ? p.no(new Error(message.error.message)) : p.yes(message.result); } }
    if (message.method === 'Runtime.exceptionThrown') errors.push(message.params.exceptionDetails.text + ': ' + message.params.exceptionDetails.exception?.description);
  };
  const send = (method, params = {}) => new Promise((yes, no) => { const n = ++id; pending.set(n, { yes, no, timer: setTimeout(() => no(new Error(`CDP timeout: ${method}`)), 10000) }); ws.send(JSON.stringify({ id: n, method, params })); });
  const evaluate = async expression => { const r = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw new Error(r.exceptionDetails.exception?.description || r.exceptionDetails.text); return r.result.value; };
  const until = async expression => { for (let i = 0; i < 60; i++) { if (await evaluate(expression)) return; await new Promise(r => setTimeout(r, 100)); } throw new Error(`UI timeout: ${expression}`); };
  const click = selector => evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const screenshot = async name => { const { data } = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true }); await writeFile(resolve(artifacts, name), Buffer.from(data, 'base64')); };
  await send('Runtime.enable'); await send('Page.enable');
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false });
  await send('Page.navigate', { url: 'http://127.0.0.1:4173' });
  await until('document.querySelectorAll(".driver-setting").length >= 1');
  await evaluate('localStorage.clear(); location.reload()');
  await until('document.querySelectorAll(".driver-setting").length === 2');
  assert.equal(await evaluate('document.documentElement.lang'), 'en');
  const originalPreview = await evaluate('document.querySelector("#course-preview").toDataURL()');
  await click('#shuffle');
  assert.notEqual(await evaluate('document.querySelector("#course-preview").toDataURL()'), originalPreview, 'A new seed visibly changes the circuit preview.');
  await evaluate('{const e=document.querySelector("#circuit-length");e.value="long";e.dispatchEvent(new Event("change"));}');
  const longLength = await evaluate('Number(document.querySelector("#course-preview").dataset.length)');
  await evaluate('{const e=document.querySelector("#circuit-length");e.value="short";e.dispatchEvent(new Event("change"));}');
  assert.ok(await evaluate('Number(document.querySelector("#course-preview").dataset.length)') < longLength);
  await evaluate('{const e=document.querySelector("#circuit-turns");e.value="technical";e.dispatchEvent(new Event("change"));const w=document.querySelector("#circuit-width");w.value="mixed";w.dispatchEvent(new Event("change"));}');
  assert.ok(await evaluate('Number(document.querySelector("#course-preview").dataset.corners)') >= 19);
  await screenshot('technical-circuit-setup.png');
  await click('#setup-form button[type="submit"]');
  assert.deepEqual(await evaluate('JSON.parse(localStorage.getItem("vector-rally-settings")).circuitOptions'), { length: 'short', turns: 'technical', width: 'mixed', shortcuts: true });
  await evaluate('location.reload()'); await until('document.querySelectorAll(".driver-setting").length === 2');
  assert.equal(await evaluate('document.querySelector("#circuit-turns").value'), 'technical');
  await evaluate('localStorage.clear(); location.reload()'); await until('document.querySelectorAll(".driver-setting").length === 2');
  await screenshot('desktop-setup.png');
  await click('#add-driver'); assert.equal(await evaluate('document.querySelectorAll(".driver-setting").length'), 3);
  await click('#driver-settings .remove-driver'); assert.equal(await evaluate('document.querySelectorAll(".driver-setting").length'), 2);
  await evaluate('localStorage.clear(); location.reload()'); await until('document.querySelectorAll(".driver-setting").length === 2');
  await evaluate('(async()=>{const e=await import("./engine.js");for(let i=0;i<100;i++){const seed="RIGHT-UI-"+i,t=e.generateTrack(seed);if(t.start.dx===1){const input=document.querySelector("#seed");input.value=seed;input.dispatchEvent(new Event("change"));return;}}throw Error("No right-facing fixture");})()');
  await click('#setup-form button[type="submit"]');
  await until('document.querySelectorAll(".destination").length === 9');
  assert.equal(await evaluate('document.querySelector("#track").clientWidth === innerWidth && document.querySelector("#track").clientHeight === innerHeight'), true);
  assert.match(await evaluate('document.querySelector("#announcement").textContent'), /Head right/);
  const pointerClick = async selector => {
    const p = await evaluate('(()=>{const r=document.querySelector(' + JSON.stringify(selector) + ').getBoundingClientRect(); return {x:r.x+r.width/2,y:r.y+r.height/2};})()');
    await send('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'left', clickCount: 1, ...p });
    await send('Input.dispatchMouseEvent', { type: 'mouseReleased', button: 'left', clickCount: 1, ...p });
  };
  assert.equal(await evaluate('[...document.querySelectorAll(".destination")].every(b => b.textContent === "")'), true, 'Landing cells contain no arrows or keyboard letters.');
  const target = '.destination[data-ax="1"][data-ay="0"]';
  await pointerClick(target);
  assert.equal(await evaluate('document.querySelector("#destinations").hidden'), true, 'The matrix disappears immediately after a move.');
  await until('document.querySelector("#game").dataset.active === "1" && document.querySelector("#game").dataset.busy === "false"');
  assert.equal(await evaluate('document.querySelector("#destinations").hidden'), true, 'The matrix stays hidden while the AI plans its turn.');
  await until('document.querySelector("#game").dataset.turns === "2" && document.querySelector("#game").dataset.busy === "false"');
  assert.equal(await evaluate('document.querySelector("#destinations").hidden'), false, 'The matrix returns for the next human turn.');
  assert.equal(await evaluate('document.querySelector("#speed").title'), 'Velocity (1, 0)');
  assert.equal(await evaluate('document.querySelectorAll(".destination").length'), 9);
  await screenshot('desktop-race.png');
  const rect = () => evaluate('(()=>{const r=document.querySelector(' + JSON.stringify(target) + ').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,width:r.width};})()');
  const assertLandingGrid = async () => {
    const cells = await evaluate('(()=>{const pad=document.querySelector("#destinations"),r=pad.getBoundingClientRect(),canvas=document.querySelector("#track"),d=canvas.dataset;return {x:r.x+r.width/2,y:r.y+r.height/2,...pad.dataset,cameraX:+d.cameraX,cameraY:+d.cameraY,zoom:+d.zoom,width:canvas.clientWidth,height:canvas.clientHeight,buttons:[...pad.children].map(b=>{const r=b.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,worldX:+b.dataset.x,worldY:+b.dataset.y};})};})()');
    assert.ok(Math.abs(cells.x - cells.carX - cells.vx * cells.cell) < 1);
    assert.ok(Math.abs(cells.y - cells.carY - cells.vy * cells.cell) < 1, 'Matrix center includes current momentum.');
    for (const b of cells.buttons) {
      assert.ok(Math.abs(b.x - ((b.worldX + .5) * 32 - cells.cameraX) * cells.zoom - cells.width / 2) < 1, 'Clicked square matches its actual landing column.');
      assert.ok(Math.abs(b.y - ((b.worldY + .5) * 32 - cells.cameraY) * cells.zoom - cells.height / 2) < 1, 'Clicked square matches its actual landing row.');
    }
  };
  const camera = () => evaluate('({...document.querySelector("#track").dataset})');
  const before = await rect(), cameraBefore = await camera();
  await assertLandingGrid();
  await send('Input.dispatchMouseEvent', { type: 'mouseWheel', x: 900, y: 380, deltaY: -180, deltaX: 0 });
  await until('Number(document.querySelector("#track").dataset.zoom) > ' + cameraBefore.zoom);
  const zoomed = await rect(), cameraZoomed = await camera();
  assert.ok(zoomed.width > before.width, 'Landing cells zoom with the track grid.');
  await assertLandingGrid();
  for (const [axis, offset] of [['X', 900 - 720], ['Y', 380 - 450]]) {
    const worldBefore = Number(cameraBefore['camera' + axis]) + offset / cameraBefore.zoom;
    const worldAfter = Number(cameraZoomed['camera' + axis]) + offset / cameraZoomed.zoom;
    assert.ok(Math.abs(worldBefore - worldAfter) < .001, 'Wheel zoom stays anchored at the cursor.');
  }
  await send('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'left', clickCount: 1, x: 400, y: 270 });
  await send('Input.dispatchMouseEvent', { type: 'mouseMoved', button: 'left', buttons: 1, x: 480, y: 300 });
  await send('Input.dispatchMouseEvent', { type: 'mouseReleased', button: 'left', clickCount: 1, x: 480, y: 300 });
  const panned = await rect(), cameraPanned = await camera();
  assert.ok(Math.abs(panned.x - zoomed.x - 80) < 2, 'The pad follows the car during a pan.');
  await assertLandingGrid();
  assert.ok(Math.abs((cameraZoomed.cameraX - cameraPanned.cameraX) * cameraZoomed.zoom - 80) < 2);
  assert.equal(await evaluate('document.querySelector("#game").dataset.turns'), '2', 'Dragging never takes a turn.');
  await pointerClick(target);
  await until('document.querySelector("#game").dataset.turns === "4" && document.querySelector("#game").dataset.busy === "false"');
  assert.equal(await evaluate('document.querySelector("#speed").title'), 'Velocity (2, 0)');
  await assertLandingGrid();
  await click('#focus-car');
  await click('#help-button'); assert.equal(await evaluate('document.querySelector("#help-dialog").open'), true);
  assert.equal(await evaluate('document.querySelector("#destinations").hidden'), true, 'Paused races hide the matrix.');
  await click('#got-it'); await until('!document.querySelector("#destinations").hidden && document.querySelectorAll(".destination").length === 9');
  await click('#overview'); await screenshot('desktop-overview.png'); await click('#focus-car');
  await pointerClick('#fullscreen'); await until('!!document.fullscreenElement');
  await pointerClick('#fullscreen'); await until('!document.fullscreenElement');
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await click('#focus-car');
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight'), true);
  await screenshot('mobile-race.png');
  await assertLandingGrid();
  assert.equal(await evaluate('(()=>{const r=document.querySelector("#destinations").getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;})()'), true);
  const mobile = await rect(); assert.ok(mobile.width >= 40, 'Mobile movement controls are large enough to tap: ' + JSON.stringify(mobile));
  await pointerClick(target); await until('document.querySelector("#game").dataset.turns === "6" && document.querySelector("#game").dataset.busy === "false"');
  await click('#menu-button'); await click('#new-race');
  await until('!document.querySelector("#setup-panel").hidden');
  const seed = await evaluate('document.querySelector("#seed").value'); await click('#shuffle');
  assert.notEqual(await evaluate('document.querySelector("#seed").value'), seed);
  // A solo stationary driver allows precise double-click and keyboard checks.
  await evaluate('(async()=>{const e=await import("./engine.js");for(let i=0;i<100;i++){const seed="KEYBOARD-UI-"+i,t=e.generateTrack(seed);if(t.start.dx===1&&[1,2,3,4,5,6].every(n=>t.road.has(e.key(t.start.x+n,t.start.y)))){const input=document.querySelector("#seed");input.value=seed;input.dispatchEvent(new Event("change"));return;}}throw Error("No keyboard fixture");})()');
  await click('#ambience');
  await click('#driver-settings .remove-driver');
  await evaluate('const control=document.querySelector("#driver-settings select");control.value="human";control.dispatchEvent(new Event("change"));');
  await click('#setup-form button[type="submit"]'); await until('document.querySelectorAll(".destination").length === 9');
  await evaluate('const b=document.querySelector(".destination[data-ax=\\"1\\"][data-ay=\\"0\\"]");b.click();b.click();');
  await until('document.querySelector("#game").dataset.busy === "false"');
  assert.equal(await evaluate('document.querySelector("#game").dataset.turns'), '1', 'Double-click only consumes one turn.');
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'd', code: 'KeyD', text: 'd' });
  await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'd', code: 'KeyD' });
  await until('document.querySelector("#game").dataset.turns === "2" && document.querySelector("#game").dataset.busy === "false"');

  const pressKey = async (key, code) => {
    await send('Input.dispatchKeyEvent', { type: 'keyDown', key, code });
    await send('Input.dispatchKeyEvent', { type: 'keyUp', key, code });
    await until('document.querySelector("#game").dataset.busy === "false"');
  };
  await pressKey('s', 'KeyS');
  assert.equal(await evaluate('document.querySelector("#speed").title'), 'Velocity (2, 0)', 'Center keeps momentum.');
  await assertLandingGrid();
  const brakeTarget = '.destination[data-ax="-1"][data-ay="0"]';
  const expected = await evaluate('({...document.querySelector(' + JSON.stringify(brakeTarget) + ').dataset})');
  await pointerClick(brakeTarget);
  await until('document.querySelector("#game").dataset.busy === "false"');
  assert.equal(await evaluate('document.querySelector("#speed").title'), 'Velocity (1, 0)', 'The cell behind the momentum center brakes.');
  const landed = await evaluate('(()=>{const p=document.querySelector("#destinations").dataset,c=document.querySelector("#track"),d=c.dataset;return {x:((p.carX-c.clientWidth/2)/d.zoom+ +d.cameraX)/32-.5,y:((p.carY-c.clientHeight/2)/d.zoom+ +d.cameraY)/32-.5};})()');
  assert.ok(Math.abs(landed.x - expected.x) < .001 && Math.abs(landed.y - expected.y) < .001, 'The car ends in the exact clicked grid cell.');
  await pressKey('ArrowLeft', 'ArrowLeft');
  assert.equal(await evaluate('document.querySelector("#speed").title'), 'Velocity (0, 0)', 'Left brakes a slow rightward car to rest.');
  await assertLandingGrid();
  await evaluate('document.activeElement.blur()'); await pressKey(' ', 'Space');
  assert.equal(await evaluate('document.querySelector("#speed").title'), 'Velocity (0, 0)', 'Space preserves momentum.');
  await screenshot('momentum-grid-mobile.png');
  const liveTurns = await evaluate('document.querySelector("#game").dataset.turns');
  await click('#replay-button');
  await until('Number(document.querySelector("#replay-panel").dataset.time) > .15');
  assert.equal(await evaluate('document.querySelector("#destinations").hidden'), true);
  await click('#replay-toggle');
  const pausedTime = await evaluate('document.querySelector("#replay-panel").dataset.time');
  await evaluate('new Promise(resolve => setTimeout(resolve, 150))');
  assert.equal(await evaluate('document.querySelector("#replay-panel").dataset.time'), pausedTime, 'Pause freezes replay.');
  await evaluate('{const seek=document.querySelector("#replay-position");seek.value="1.25";seek.dispatchEvent(new Event("input"));}');
  assert.equal(await evaluate('document.querySelector("#replay-panel").dataset.time'), '1.2500');
  await click('#replay-back'); assert.equal(await evaluate('document.querySelector("#replay-panel").dataset.time'), '1.0000');
  await click('#replay-forward'); assert.equal(await evaluate('document.querySelector("#replay-panel").dataset.time'), '2.0000');
  await evaluate('const speed=document.querySelector("#replay-speed");speed.value="4";speed.dispatchEvent(new Event("change"));');
  assert.equal(await evaluate('document.querySelector("#replay-panel").dataset.speed'), '4');
  await screenshot('mobile-replay.png');
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false });
  await screenshot('desktop-replay.png');
  await click('#replay-toggle'); await until('Number(document.querySelector("#replay-panel").dataset.time) > 2.25');
  await click('#replay-toggle');
  assert.equal(await evaluate('document.querySelector("#game").dataset.turns'), liveTurns, 'Replay never consumes live turns.');
  await click('#replay-close');
  assert.equal(await evaluate('document.querySelector("#replay-panel").hidden'), true);
  assert.equal(await evaluate('document.querySelector("#destinations").hidden'), false, 'Returning restores the human turn.');
  // Theme choice, remembered settings, live scenery and pause/reduced-motion behavior.
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false });
  for (const theme of ['forest', 'sand', 'future']) {
    await click('#menu-button'); await click('#new-race');
    if (theme === 'forest') await click('#ambience');
    await click('.theme-option[data-theme="' + theme + '"]');
    assert.equal(await evaluate('document.querySelector("#track").dataset.theme'), theme);
    await screenshot('theme-' + theme + '-setup.png');
    await click('#setup-form button[type="submit"]');
    await until('Number(document.querySelector("#track").dataset.sceneryTime) > .15');
    assert.equal(await evaluate('JSON.parse(localStorage.getItem("vector-rally-settings")).themeId'), theme);
    const turns = await evaluate('document.querySelector("#game").dataset.turns');
    await screenshot('theme-' + theme + '-race.png');
    await click('#help-button');
    const frozen = await evaluate('document.querySelector("#track").dataset.sceneryTime');
    await evaluate('new Promise(resolve => setTimeout(resolve, 180))');
    assert.equal(await evaluate('document.querySelector("#track").dataset.sceneryTime'), frozen, 'Help pauses wildlife.');
    assert.equal(await evaluate('document.querySelector("#game").dataset.turns'), turns, 'Scenery does not consume turns.');
    await click('#got-it');
    await until('Number(document.querySelector("#track").dataset.sceneryTime) > ' + Number(frozen));
  }
  await click('#menu-button'); await click('#new-race'); await click('#ambience');
  await click('#setup-form button[type="submit"]');
  await evaluate('new Promise(resolve => setTimeout(resolve, 180))');
  assert.equal(await evaluate('document.querySelector("#track").dataset.sceneryTime'), '0.000', 'Scenery toggle stops the ambient loop.');
  await evaluate('location.reload()'); await until('document.querySelectorAll(".theme-option").length === 7');
  assert.equal(await evaluate('document.querySelector("#track").dataset.theme'), 'future', 'Theme survives reload.');
  assert.equal(await evaluate('document.querySelector("#ambience").checked'), false, 'Scenery preference survives reload.');
  await click('#ambience');
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] });
  await click('#setup-form button[type="submit"]');
  await evaluate('new Promise(resolve => setTimeout(resolve, 180))');
  assert.equal(await evaluate('document.querySelector("#track").dataset.sceneryTime'), '0.000', 'Reduced motion keeps wildlife still.');
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] });
  await until('Number(document.querySelector("#track").dataset.sceneryTime) > .1');
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await click('#menu-button'); await click('#new-race'); await screenshot('mobile-theme-setup.png');
  assert.equal(await evaluate('document.querySelector("#theme-options").scrollWidth <= document.querySelector("#theme-options").clientWidth'), true);
  // Freeze a known perched bird to test the actual UI-to-engine collision path.
  await click('.theme-option[data-theme="forest"]');
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] });
  await evaluate('(async()=>{const e=await import("./engine.js"),s=await import("./themes.js");for(let i=0;i<150;i++){const seed="WILDLIFE-UI-"+i,t=e.generateTrack(seed),cells=s.wildlifeCells(s.createScenery(t,"forest")),x=t.start.x,y=t.start.y;if(t.start.dx===1&&cells.has(e.key(x+6,y))&&!cells.has(e.key(x+1,y))&&!cells.has(e.key(x+3,y))&&e.previewMove(t,{id:0,x:x+3,y,vx:2,vy:0,slowTurns:0},{ax:1,ay:0},[],cells).reason==="Animal on the landing cell"){const input=document.querySelector("#seed");input.value=seed;input.dispatchEvent(new Event("change"));return;}}throw Error("No wildlife fixture");})()');
  await click('#setup-form button[type="submit"]');
  for (let i = 0; i < 2; i++) { await pointerClick(target); await until('document.querySelector("#game").dataset.busy === "false"'); }
  const animalTarget = '.destination[data-ax="1"][data-ay="0"]';
  const escapeTarget = '.destination[data-ax="-1"][data-ay="0"]';
  assert.match(await evaluate('document.querySelector(' + JSON.stringify(animalTarget) + ').title'), /Animal on the landing cell/);
  assert.equal(await evaluate('document.querySelector(' + JSON.stringify(animalTarget) + ').classList.contains("danger")'), true);
  await pointerClick(animalTarget); await until('document.querySelector("#game").dataset.busy === "false"');
  assert.equal(await evaluate('document.querySelector("#speed").title'), 'Velocity (0, 0)');
  assert.equal(await evaluate('document.querySelector("#recover")'), null, 'Crashes never require skipping a turn.');
  assert.equal(await evaluate('document.querySelector("#destinations").hidden'), false, 'Driving is available immediately after impact.');
  assert.match(await evaluate('document.querySelector("#move-description").textContent'), /Speed limit 1.*3 turns/);
  await pointerClick(escapeTarget); await until('document.querySelector("#game").dataset.busy === "false"');
  assert.equal(await evaluate('document.querySelector("#speed").title'), 'Velocity (-1, 0)', 'Drive away immediately after crashing.');
  assert.equal(await evaluate('document.querySelector(' + JSON.stringify(escapeTarget) + ').disabled'), true, 'Acceleration beyond speed one is unavailable.');
  const coastTarget = '.destination[data-ax="0"][data-ay="0"]';
  for (let i = 0; i < 2; i++) { await pointerClick(coastTarget); await until('document.querySelector("#game").dataset.busy === "false"'); }
  assert.equal(await evaluate('document.querySelector(' + JSON.stringify(escapeTarget) + ').disabled'), false, 'Normal acceleration returns after three driving turns.');
  await click('#replay-button'); await click('#replay-toggle');
  await evaluate('{const seek=document.querySelector("#replay-position");seek.value="2.5";seek.dispatchEvent(new Event("input"));}');
  await screenshot('wildlife-crash-replay.png');
  await evaluate('{const seek=document.querySelector("#replay-position");seek.value="0";seek.dispatchEvent(new Event("input"));}');
  await click('#replay-toggle');
  const cadence = await evaluate('new Promise(resolve=>{const times=[];function frame(t){times.push(t);if(times.length<90)requestAnimationFrame(frame);else resolve(1000*(times.length-1)/(times.at(-1)-times[0]));}requestAnimationFrame(frame);})');
  console.log('Observed replay display cadence: ' + cadence.toFixed(1) + ' fps (hardware-dependent).');
  await click('#replay-close');
  assert.deepEqual(errors, []);
  console.log('Browser smoke passed: three themes, remembered settings, ambient pause/toggle/reduced motion, single-click movement, AI response, cursor-anchored wheel zoom, pan without movement, clicking after camera transforms, fullscreen, mobile targets, help/menu, replay, double-click lock and immediate keyboard turns.');
  console.log('Screenshots: ' + artifacts);
} finally { ws?.close(); child.kill(); }
